import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fleetDir, localDir, manifestPath, SKILLS, RULES, MCP } from "./store.js";
import { syncMcpServers, claudeRunner, type McpRunner } from "./mcp.js";
import { walkFiles, pruneEmptyDirs } from "./apply.js";

// Projection: `~/.agents/{fleet,local}` → each agent tool's native location (docs/design.md §4).
//
// The store is tool-agnostic; the tools are not. This is where one canonical copy becomes whatever
// Claude Code (and later Codex, pi) actually reads.
//
// Copy, never symlink: a Windows symlink needs administrator or developer mode, which a
// cross-platform tool cannot depend on.

export interface ProjectionResult {
  written: string[];
  removed: string[];
  /** Skill ids where a local copy shadowed a hub-managed one. Surfaced, never silently merged. */
  conflicts: string[];
  mcp: { added: string[]; removed: string[]; skipped: boolean; warnings: string[] };
}

interface Manifest {
  version: number;
  files: string[];
  /** MCP server ids cc-fleet added. The ONLY way to know which are ours to remove — we cannot read
   *  ~/.claude.json to find out, by design. */
  mcpServers?: string[];
  projectedAt: number;
}

const MANIFEST_VERSION = 1;
const GENERATED_HEADER = [
  "<!-- GENERATED BY cc-fleet — DO NOT EDIT.",
  "     Edits here are overwritten on the next apply.",
  "     Author rules in ~/.agents/local/rules/ instead. -->",
  "",
].join("\n");

function readManifest(agents: string): Manifest | null {
  const p = manifestPath(agents);
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, "utf8")) as Manifest;
    return Array.isArray(raw?.files) ? raw : null;
  } catch { return null; } // a corrupt manifest degrades to full takeover, never to a crash
}

function writeManifest(agents: string, files: string[], mcpServers: string[], now: number): void {
  const p = manifestPath(agents);
  mkdirSync(dirname(p), { recursive: true });
  const data: Manifest = { version: MANIFEST_VERSION, files: [...files].sort(), mcpServers: [...mcpServers].sort(), projectedAt: now };
  writeFileSync(p, JSON.stringify(data, null, 2), { mode: 0o600 });
}

/** MCP configs from one store half: id -> parsed config. Unparseable files are skipped, not fatal. */
function mcpConfigs(root: string, warnings: string[]): Map<string, Record<string, unknown>> {
  const dir = join(root, MCP);
  const out = new Map<string, Record<string, unknown>>();
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".json") || !statSync(join(dir, name)).isFile()) continue;
    const id = name.replace(/\.json$/, "");
    try { out.set(id, JSON.parse(readFileSync(join(dir, name), "utf8")) as Record<string, unknown>); }
    catch { warnings.push(`mcp config ${id} is not valid JSON — skipped`); }
  }
  return out;
}

/** Skill ids present in a store half, in directory order. */
function skillIds(root: string): string[] {
  const dir = join(root, SKILLS);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((n) => statSync(join(dir, n)).isDirectory());
}

/** `<id>/<relative path>` → absolute source, for one store half. */
function skillFiles(root: string, id: string): Map<string, string> {
  const base = join(root, SKILLS, id);
  const out = new Map<string, string>();
  for (const rel of walkFiles(base)) out.set(`${id}/${rel}`, join(base, ...rel.split("/")));
  return out;
}

function ruleFiles(root: string): { id: string; abs: string }[] {
  const dir = join(root, RULES);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((n) => n.endsWith(".md") && statSync(join(dir, n)).isFile())
    .sort()
    .map((n) => ({ id: n.replace(/\.md$/, ""), abs: join(dir, n) }));
}

export interface ProjectOptions {
  now?: () => number;
  /** Injectable so tests never shell out to a real `claude`. */
  mcpRunner?: McpRunner;
}

export function project(agents: string, claudeHome: string, opts: ProjectOptions = {}): ProjectionResult {
  const fleet = fleetDir(agents);
  const local = localDir(agents);
  const conflicts: string[] = [];

  // ── skills: same id means the SAME THING in two versions, so exactly one may win ──────────────
  // local wins: the person at the machine knows more about what it needs than a remote profile does,
  // and this is what makes a temporary local override of a managed skill possible at all.
  const merged = new Map<string, string>(); // target-relative path -> absolute source
  const fleetIds = new Set(skillIds(fleet));
  for (const id of fleetIds) for (const [k, v] of skillFiles(fleet, id)) merged.set(k, v);
  for (const id of skillIds(local)) {
    if (fleetIds.has(id)) {
      conflicts.push(id);
      // Drop the fleet copy entirely rather than merging file-by-file: half of one version and half
      // of another is a skill that exists in neither store and that nobody wrote.
      for (const k of [...merged.keys()]) if (k === id || k.startsWith(`${id}/`)) merged.delete(k);
    }
    for (const [k, v] of skillFiles(local, id)) merged.set(k, v);
  }

  const skillsTarget = join(claudeHome, SKILLS);
  const desired = new Map<string, string>();
  for (const [rel, src] of merged) desired.set(`${SKILLS}/${rel}`, src);

  // ── rules: independent constraints, so they ACCUMULATE — fleet first, then local ──────────────
  const rules = [
    ...ruleFiles(fleet).map((r) => ({ ...r, from: "fleet" })),
    ...ruleFiles(local).map((r) => ({ ...r, from: "local" })),
  ];
  const rulesTarget = join(claudeHome, "CLAUDE.md");

  // ── write ────────────────────────────────────────────────────────────────────────────────────
  const written: string[] = [];
  const removed: string[] = [];

  mkdirSync(skillsTarget, { recursive: true });
  // Full takeover of the target (design v2 §4): anything not projected is deleted. Consistent with
  // M1, and the reason `~/.agents/local/` exists — that, not this directory, is where a person edits.
  for (const rel of walkFiles(skillsTarget)) {
    if (!desired.has(`${SKILLS}/${rel}`)) {
      rmSync(join(skillsTarget, ...rel.split("/")), { force: true });
      removed.push(`${SKILLS}/${rel}`);
    }
  }
  pruneEmptyDirs(skillsTarget);

  for (const [rel, src] of desired) {
    const dest = join(claudeHome, ...rel.split("/"));
    const content = readFileSync(src);
    if (existsSync(dest)) {
      try { if (readFileSync(dest).equals(content)) { written.push(rel); continue; } } catch { /* rewrite */ }
    }
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, content);
    written.push(rel);
  }

  if (rules.length) {    const body = rules
      .map((r) => `<!-- cc-fleet: ${r.from}/rules/${r.id}.md -->\n${readFileSync(r.abs, "utf8").trimEnd()}\n`)
      .join("\n");
    writeFileSync(rulesTarget, `${GENERATED_HEADER}\n${body}`);
    written.push("CLAUDE.md");
  } else {
    // No rules means no rules. Under full takeover that legitimately removes the generated file —
    // but ONLY if we generated it: a hand-written CLAUDE.md that predates cc-fleet is not ours to
    // delete, and the manifest is the only way to tell the two apart.
    const prior = readManifest(agents);
    if (existsSync(rulesTarget) && prior?.files.includes("CLAUDE.md")) {
      rmSync(rulesTarget, { force: true });
      removed.push("CLAUDE.md");
    }
  }

  // ── MCP: same merge rule as skills (local wins on id), but projected through Claude Code's own
  //    CLI rather than by writing its config file. See mcp.ts for why that boundary is absolute.
  const mcpWarnings: string[] = [];
  const mcpDesired = mcpConfigs(fleet, mcpWarnings);
  for (const [id, cfg] of mcpConfigs(local, mcpWarnings)) mcpDesired.set(id, cfg);
  const previous = readManifest(agents);
  const mcpResult = syncMcpServers(
    { desired: mcpDesired, previouslyAdded: previous?.mcpServers ?? [] },
    opts.mcpRunner ?? claudeRunner(),
  );

  writeManifest(agents, written, mcpResult.managed, opts.now?.() ?? Date.now());
  return {
    written: written.sort(),
    removed: removed.sort(),
    conflicts: conflicts.sort(),
    mcp: { added: mcpResult.added, removed: mcpResult.removed, skipped: mcpResult.skipped, warnings: mcpWarnings.concat(mcpResult.warnings) },
  };
}
