import { describe, it, expect, afterEach, vi } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { startControlHub, type RunningHub } from "../src/control/hub/index.js";
import { connectHttp } from "../src/control/transport/http-agent.js";
import { startAgent, type RunningAgent } from "../src/control/agent/agent.js";
import { fleetDir, localDir } from "../src/control/agent/store.js";

// M2 end to end over real HTTP: the hub's profile lands in the tool-agnostic store, the store is
// projected into Claude Code, and the node's own half survives all of it.
//
// The layered store only earns its extra indirection if all three hold at once, so they are asserted
// together rather than in isolation.

const DEVICE = "laptop-home";
const cleanups: (() => void)[] = [];
afterEach(() => { for (const c of cleanups.splice(0).reverse()) c(); });

const profile = (version: number, skills: unknown[], rules: unknown[] = []) => ({
  version,
  groups: { full: { skills, rules } },
  assignments: { [DEVICE]: "full" },
});
const skill = (id: string, content: string) => ({ id, files: [{ path: "SKILL.md", content }] });

async function hubWith(initial: unknown) {
  const dataDir = mkdtempSync(join(tmpdir(), "cchub-"));
  writeFileSync(join(dataDir, "profile.json"), JSON.stringify(initial, null, 2));
  const hub = await startControlHub({ dataDir, port: 0, host: "127.0.0.1", keepAliveMs: 200, debounceMs: 20 });
  cleanups.push(() => hub.close());
  return Object.assign(hub, {
    dataDir,
    writeProfile: (p: unknown) => writeFileSync(join(dataDir, "profile.json"), JSON.stringify(p, null, 2)),
  });
}

interface Node { agents: string; claude: string }
const tokens = new Map<string, string>();
afterEach(() => tokens.clear());

function node(hub: RunningHub, n: Node): RunningAgent {
  const key = `${hub.port}:${DEVICE}`;
  let token = tokens.get(key);
  if (!token) {
    token = hub.devices.enroll({ hostname: DEVICE, os: "linux", agentVersion: "e2e" }).deviceToken;
    tokens.set(key, token);
  }
  const channel = connectHttp({ hubUrl: `http://127.0.0.1:${hub.port}`, token, deviceId: DEVICE, retryMs: 20, maxRetryMs: 100 });
  const agent = startAgent({ agentsHome: n.agents, claudeHome: n.claude, channel, deviceId: DEVICE, agentVersion: "e2e" });
  cleanups.push(() => { agent.stop(); channel.close(); });
  return agent;
}

const fresh = (): Node => ({
  agents: mkdtempSync(join(tmpdir(), "agents-")),
  claude: mkdtempSync(join(tmpdir(), "claude-")),
});
const read = (...p: string[]) => readFileSync(join(...p), "utf8");

describe("control M2 — store and projection", () => {
  it("lands a pushed skill in the store AND in Claude Code's directory", async () => {
    const hub = await hubWith(profile(1, [skill("code-review", "review carefully")]));
    const n = fresh();
    node(hub, n);
    await vi.waitFor(() => {
      expect(read(fleetDir(n.agents), "skills", "code-review", "SKILL.md")).toBe("review carefully");
      expect(read(n.claude, "skills", "code-review", "SKILL.md")).toBe("review carefully");
    }, { timeout: 10000 });
  }, 20000);

  it("projects rules into a generated CLAUDE.md, in order, labelled by origin", async () => {
    const hub = await hubWith(profile(1, [], [
      { id: "b-second", content: "SECOND RULE" },
      { id: "a-first", content: "FIRST RULE" },
    ]));
    const n = fresh();
    node(hub, n);
    await vi.waitFor(() => expect(existsSync(join(n.claude, "CLAUDE.md"))).toBe(true), { timeout: 10000 });
    const md = read(n.claude, "CLAUDE.md");
    expect(md.indexOf("FIRST RULE")).toBeLessThan(md.indexOf("SECOND RULE"));
    expect(md).toMatch(/GENERATED BY cc-fleet/);
    expect(md).toContain("cc-fleet: fleet/rules/a-first.md");
  }, 20000);

  it("never touches the node's own half, and still projects it into the tool", async () => {
    // This is the whole point of M2: before it, "the hub decides" and "I can add a skill here" were
    // mutually exclusive.
    const hub = await hubWith(profile(1, [skill("from-hub", "hub")]));
    const n = fresh();
    mkdirSync(join(localDir(n.agents), "skills", "mine"), { recursive: true });
    writeFileSync(join(localDir(n.agents), "skills", "mine", "SKILL.md"), "my own work");

    node(hub, n);
    await vi.waitFor(() => expect(existsSync(join(n.claude, "skills", "from-hub"))).toBe(true), { timeout: 10000 });
    expect(read(localDir(n.agents), "skills", "mine", "SKILL.md")).toBe("my own work");
    expect(read(n.claude, "skills", "mine", "SKILL.md")).toBe("my own work");

    // And it survives a subsequent full-takeover push that knows nothing about it.
    hub.writeProfile(profile(2, [skill("from-hub", "hub v2")]));
    await vi.waitFor(() => expect(read(n.claude, "skills", "from-hub", "SKILL.md")).toBe("hub v2"), { timeout: 5000 });
    expect(read(localDir(n.agents), "skills", "mine", "SKILL.md")).toBe("my own work");
  }, 30000);

  it("lets a local skill shadow the hub's copy, and says so", async () => {
    const hub = await hubWith(profile(1, [skill("dup", "hub version")]));
    const n = fresh();
    mkdirSync(join(localDir(n.agents), "skills", "dup"), { recursive: true });
    writeFileSync(join(localDir(n.agents), "skills", "dup", "SKILL.md"), "local version");

    const agent = node(hub, n);
    await vi.waitFor(() => expect(read(n.claude, "skills", "dup", "SKILL.md")).toBe("local version"), { timeout: 10000 });
    // The hub's copy is still in the store — shadowed, not lost.
    expect(read(fleetDir(n.agents), "skills", "dup", "SKILL.md")).toBe("hub version");
    expect(agent.status().conflicts).toEqual(["dup"]);
    await vi.waitFor(() => {
      const last = hub.hub.lastApplied(DEVICE);
      expect(last?.warnings.join(" ")).toMatch(/overrides the fleet copy/);
    }, { timeout: 10000 });
  }, 20000);

  it("takes over the tool's directory, backing up what it removes", async () => {
    const hub = await hubWith(profile(1, [skill("managed", "x")]));
    const n = fresh();
    mkdirSync(join(n.claude, "skills", "stale"), { recursive: true });
    writeFileSync(join(n.claude, "skills", "stale", "SKILL.md"), "hand placed, not in the store");

    node(hub, n);
    await vi.waitFor(() => expect(existsSync(join(n.claude, "skills", "stale"))).toBe(false), { timeout: 10000 });
    expect(existsSync(join(n.agents, ".cc-fleet", "backups"))).toBe(true);
  }, 20000);

  it("rescues a pre-M2 hand-placed skill into local/ instead of deleting it", async () => {
    // Upgrading from M1: ~/.claude/skills holds hub content and the user's own, with nothing marking
    // which is which. Only the ids the profile does NOT claim may move, or a managed skill would
    // become a local override that shadows the hub forever.
    const hub = await hubWith(profile(1, [skill("code-review", "hub copy")]));
    const claude = mkdtempSync(join(tmpdir(), "claude-"));
    const agents = join(mkdtempSync(join(tmpdir(), "root-")), ".agents"); // store not created yet
    mkdirSync(join(claude, "skills", "code-review"), { recursive: true });
    writeFileSync(join(claude, "skills", "code-review", "SKILL.md"), "stale hub copy");
    mkdirSync(join(claude, "skills", "my-own"), { recursive: true });
    writeFileSync(join(claude, "skills", "my-own", "SKILL.md"), "mine");

    node(hub, { agents, claude });
    await vi.waitFor(() => expect(read(claude, "skills", "code-review", "SKILL.md")).toBe("hub copy"), { timeout: 10000 });
    expect(read(localDir(agents), "skills", "my-own", "SKILL.md")).toBe("mine");
    // The managed id must NOT have been moved into local/, or it would shadow the hub from now on.
    expect(existsSync(join(localDir(agents), "skills", "code-review"))).toBe(false);
  }, 20000);

  it("leaves identity, history and commands alone", async () => {
    const hub = await hubWith(profile(1, [skill("s", "x")]));
    const n = fresh();
    mkdirSync(join(n.claude, "projects"), { recursive: true });
    mkdirSync(join(n.claude, "commands"), { recursive: true });
    writeFileSync(join(n.claude, "projects", "session.json"), "history");
    writeFileSync(join(n.claude, "commands", "mine.md"), "my command");
    writeFileSync(join(n.claude, ".claude.json"), "creds");

    node(hub, n);
    await vi.waitFor(() => expect(existsSync(join(n.claude, "skills", "s"))).toBe(true), { timeout: 10000 });
    expect(read(n.claude, "projects", "session.json")).toBe("history");
    expect(read(n.claude, "commands", "mine.md")).toBe("my command");
    expect(read(n.claude, ".claude.json")).toBe("creds");
  }, 20000);
});
