// AUTO-GENERATED by scripts/gen-changes.mjs from CHANGELOG.md — do not edit.
export interface ChangeEntry { version: string; date: string; summary: string; summaries: string[] }
export const APP_CHANGES: ChangeEntry[] = [
  {
    "version": "0.1.0",
    "date": "2026-08-13",
    "summary": "Fork from copilot-reverse v0.21.0. Package identity, bin name and data dir (`~/.cc-fleet`) are rebranded; everything else is inherited unchanged and its 743 tests stay green. Control plane not built yet — see [`docs/design.md`](docs/design.md).",
    "summaries": [
      "Fork from copilot-reverse v0.21.0. Package identity, bin name and data dir (`~/.cc-fleet`) are rebranded; everything else is inherited unchanged and its 743 tests stay green. Control plane not built yet — see [`docs/design.md`](docs/design.md)."
    ]
  }
];
